# Generated by Django 5.2.10 on 2026-01-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("age", models.IntegerField(default=18)),
                ("Email", models.EmailField(max_length=50)),
                ("phone", models.IntegerField(default=0)),
                ("address", models.TextField()),
                ("image", models.ImageField(upload_to="images/")),
                ("file", models.FileField(upload_to="")),
            ],
        ),
    ]
