# Generated by Django 5.2.10 on 2026-01-26 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodrecipe", "0004_department_studentid_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Subjectmarks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marks", models.IntegerField()),
                (
                    "Subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="foodrecipe.subject",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studentmarks",
                        to="foodrecipe.student",
                    ),
                ),
            ],
        ),
    ]
