# Generated by Django 5.2.10 on 2026-01-28 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodrecipe", "0005_subject_subjectmarks"),
    ]

    operations = [
        migrations.CreateModel(
            name="reportcard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.IntegerField()),
                ("data_of_Edited", models.DateField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studentreport",
                        to="foodrecipe.student",
                    ),
                ),
            ],
        ),
    ]
